spring.application.name=ordem-servico

spring.datasource.url=jdbc:mysql://localhost:3306/assistencia_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=a1p2d3s4n5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.deserialization.fail-on-unknown-properties=false